---
- name: Write executable script
  ansible.builtin.template:
    src: script.j2
    dest: "{{ cronlist_destination }}"
    owner: "{{ cronlist_owner }}"
    group: "{{ cronlist_group }}"
    mode: u=rwx,g=rwx,o=rx
  tags:
    - cronlist

...
